---
title: "Lista de Exercícios 3"
date: "Entrega: **09/04/2023** via Moodle (até as 23:59)"
output: 
  html_document: 
    css: hw.css
    theme: yeti
    toc: true
    toc_float: true
    fig_caption: true
---

## 

Você irá entregar essa lista de exercício no Moodle da disciplina. Você deverá submeter preferencialmente o **arquivo pdf gerado automaticamente pelo R** usando *markdown*. 
<!-- Não serão aceitos arquivos em outro formato! -->


## Instruções

- Lembre-se das opções que você pode escolher ao inserir um *code chunk* para que apenas as informações relevantes sejam incluídas no seu relatório final. 

- Para incluir apenas o resultado final e não mostrar o código, use a opção `echo=FALSE`. Se um *chunk* contém código para plotar gráficos, utilize as opções específicas para controlar como as figuras serão impressas. Por exemplo, use a opção `fig.align` para alinhar a figura (igual a "left", "right", ou "center"), e as opções `fig.width` e `fig.height` para determinar a largura e/ou a altura da figura em polegadas (*default* = 7). Veja mais detalhes na [documentação do RMarkdown](https://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf).



## Gráficos no R


1) Plote a função $f(x) = x \cdot \log(x)$ para $x \in (0,1]$. 

   Qual é o valor de $x$ correspondente ao mínimo da função $f(x)$ nesse intervalo? Responda com um comando do R.
   
   Inclua no gráfico acima uma linha horizontal pontilhada vermelha para o valor mínimo de $f(x)$.


2) Quando plotamos $y$ versus $x$ usando `plot()`, o que a opção `asp=1` faz?


3) Quando plotamos $y$ versus $x$ usando `plot()`, o que as opções `xaxs="i"` e `yaxs="i"` fazem?


4) Quando plotamos $y$ versus $x$ usando `plot()`, o que a opção `las=3` faz?


5) Quando plotamos $y$ versus $x$ usando `plot()`, o que a opção `xlim=rev(range(x))` faz?


## Banco de Dados

- Para os exercícios a seguir, vamos usar o pacote `ggplot2` e o banco de dados de gasto de combustível `mpg`.
Para carregar os dados, você precisa ter o pacote `ggplot2` instalado. Depois, basta executar os comandos:

```{r eval=FALSE}
require(ggplot2)
mpg
```


6) Quais variáveis do banco de dados são categóricas? Quais variáveis são contínuas? (Dica: use o comando `?mpg` para ver a descrição do banco).


7) Refaça os gráficos feitos em sala para verificar a relação entre a capacidade do motor (`displ`) e o consumo do carro (`mpg`), mas com cores diferentes de acordo com o tipo de tração (`drv`) do carro. O que você observa na relação entre essas três variáveis?


8) Refaça o gráfico do exercício anterior, mas separe em diferentes painéis os pontos de cada tipo de tração usando o comando `facet_grid()`. Você acha que essa visualização facilita a comparação dos diferentes grupos de carros?


<!-- ## Resolução -->

<!-- Sugestão de respostas: -->

<!-- - [Resolução Lista 3](./resolucao/lista-03-resolucao.html) -->

<!-- - [Arquivo .Rmd](./resolucao/lista-03-resolucao.Rmd) -->
