baseurl = "/"
languageCode = "pt-br"
defaultContentLanguage = "pt-br"

title = "Métodos Computacionais para Análise de Risco 2023/1"
theme = "material"

# disqusShortname = ""
# googleAnalytics = ""

paginate = 7
relativeurls = true
publishDir = "public"
# ignoreFiles = [ "hw/resolucao/.*",  "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$" ]
ignoreFiles = [ "hw/resolucao/.*",  "\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$" ]

enableEmoji = true

[permalinks]
  post = "/:year/:month/:slug/"

# [taxonomies]
#  tag = "tags"
#  category = "categories"
#  archive = "archives"

[author]
  name = "Thais Paiva Galletti"
  bio = ""
  job = "Assistant Professor of Statistics"
  location = "Universidade Federal de Minas Gerais"
  gravatarEmail = "thaispaiva@est.ufmg.br"
  # Your profile picture
#  picture = ""
#  twitter = ""
 
# Menu Configuration
[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
  url = "/"
[[menu.main]]
  weight = 2
  identifier = "Cronograma"
  name = "Cronograma"
  pre = "<i class=\"material-icons\">date_range</i>"
  url = "/cronograma"
[[menu.main]]
  weight = 3
  identifier = "Ferramentas"
  name = "Ferramentas"
  pre = "<i class=\"material-icons\">build</i>"
  url = "/ferramentas"

[[menu.footer]]
  weight = 1
  identifier = "DEST"
  name = "DEST UFMG"
  pre = "<i class=\"button-icon fa fa-2x fa-signal\"></i>"
  url = "http://est.ufmg.br"
[[menu.footer]]
  weight = 2
  name = "Minha UFMG"
  pre = "<i class=\"button-icon fa fa-2x fa-edit\"></i>"
  url = "https://minha.ufmg.br/"
[[menu.footer]]
  weight = 3
  identifier = "GitHub"
  name = "GitHub"
  pre = "<i class=\"button-icon fa fa-2x fa-github\"></i>"
  url = "https://github.com/thaispaiva/MetComp_site_2023"


[params]
  dateFormat = "02/01/2006"
  # background = "http://career.sa.ucsb.edu/files/docs/actuary2_0.png"
  background = "https://cdn.pixabay.com/photo/2016/04/18/22/05/insurance-1337564_1280.png"
  favicon = "img/favicon.ico"
